# Source and destination directories
source: ./src
destination: ./build

# Development options for jekyll serve
livereload: true

# Custom options
title: michaelti.ca

# Custom collections
collections_dir: collections
collections:
    portfolio:
        output: true
        permalink: /:collection/:name/
        sort_by: order

# Front matter defailts
defaults:
    -
        scope:
            path: ""
            type: "portfolio"
        values:
            layout: "page"
