name: CI

on:
  push:
    branches: [ master, github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out the repository
      uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x 
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install bundler
      run: gem install bundler
    - name: Bundle install gems
      run: bundle install --jobs 4 --retry 3
    - name: Build Jekyll website
      run: bundle exec jekyll install
    - name: List directory contents
      run: ls -la
