name: CI

on:
  push:
    branches: [ master, github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out the repository
      uses: actions/checkout@v2
      
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x 
      
    - name: Set up cache for installed gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-

    - name: Bundle install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Build Jekyll website
      run: bundle exec jekyll build

    - name: List build directory contents
      run: ls -la build/
